adaptlearning/adapt-contrib-textInput

README.md
js/adapt-contrib-textInput.js

Allows answers to be specified at a question-level, rather than having to specify per input. Allows user to answer in any order.

Marking fix

---

templates/textinput.hbs

- prefix and and suffix classes are needed to apply content size specific styling.

prefix class added for styling

---

README.md
example.json
properties.schema

I have omitted generic _answers element from the schema as I think there are issues with this:
https://github.com/adaptlearning/adapt-contrib-textInput/issues/59
https://github.com/adaptlearning/adapt-contrib-textInput/issues/58

Abu 645/abu 644

---

js/adapt-contrib-textInput.js

This component is set up to be incorrect by default, changed to be undefined.

This component is set up to be incorrect.

---

js/adapt-contrib-textInput.js

* made sure restoring answers takes the first correct item in the array if generic answers is an array
* made sure marking answers doesn't destroy answerItems indexes in the saving process

Fix: save and restore issues with new features

---

README.md
example.json
js/adapt-contrib-textInput.js
properties.schema

as per [ABU-690](https://adaptlearning.atlassian.net/browse/ABU-690)
refactor randomisation code out into separate method in line with contrib-mcq
remove pointless comments
update README.md, example.json and properties.schema with new `_recordInteraction` property

add support for cmi.interactions

---

templates/textinput.hbs

Fixes #75 where _id was not being found.
Extended path from ../_id to ../../_id

_id not being found in template

---

README.md
bower.json
templates/textinput.hbs

fixes https://github.com/adaptlearning/adapt_framework/issues/1459
before:
after:

correct the path to the id property in the template

---

less/textinput.less

adaptlearning/adapt_framework#1913 
Remove IE11  "clear field" X button on certain inputs.

minor tweak.

---

less/textinput.less

Resolves https://github.com/adaptlearning/adapt_framework/issues/1755.

#1755,Doesn't show green (correct) tick on correct answer selection.

---

properties.schema
templates/textinput.hbs

[#2084](https://github.com/adaptlearning/adapt_framework/issues/2084)
* Removed component description
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: issue/#2084

---

js/textInputView.js

Fixes https://github.com/adaptlearning/adapt_framework/issues/2356

fixes JS error when submitting answer

---

example.json
js/adapt-contrib-textInput.js
js/textInputModel.js
js/textInputView.js
less/textinput.less
templates/textinput.hbs

TextInput converted to use 2 spaces for indentation.

update to use 2 spaces for indentation

---

less/textinput.less

Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891

Less tidy up

---

README.md
bower.json
js/adapt-contrib-textInput.js
js/textInputModel.js
js/textInputView.js
package.json

https://github.com/adaptlearning/adapt_framework/issues/2808

2808 - convert to es6 classes/modules, added imports, arrow functions, const/let

---

less/textinput.less
templates/textinput.hbs

Resolves https://github.com/adaptlearning/adapt-contrib-textInput/issues/107
* Converted textinput naming so each item is treated as a block within BEM

BEM naming corrections

---

bower.json
js/adapt-contrib-textInput.js

requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to components.register from Adapt.register

issue/2799 Removed redundant behaviour

---

example.json
properties.schema
schema/component.schema.json

#118 
* default instruction text provided

New: Provide default instruction text (fixes #118)

---

README.md
example.json
properties.schema
schema/component.schema.json
templates/textinput.jsx

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Adds ariaQuestion, schema & README adjustments to this component
* Fixes #121 
[//]: # (List appropriate steps for testing if needed)
1. Install PR and test in AAT
[//]: # (Mention any other dependencies)

Fix: Add ariaQuestion to component (fixes: 121)

---

templates/textinput.jsx

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Fixes #127 
[//]: # (List appropriate steps for testing if needed)
1. Pull down this PR and examine the structure in the output
[//]: # (Mention any other dependencies)

Fix: Normalizing template icons (fixes: #127)

---

test/e2e/textInput.cy.js

Chore: e2e tests on text input component (Issue/138)

---

js/textInputModel.js

part of #154 
* Do not error on missing generic _answers array

Fix: Error on missing generic _answers array

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

Fixes https://github.com/adaptlearning/adapt-contrib-textInput/issues/157
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template

Chore: Add support for new issue experience (fixes #157)
